services:
  db:
    image: postgres:17.3
    container_name: postgres-buddycount
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: backend
      POSTGRES_USER: backend

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - 8080:8080